export const enum PRODUCT_API {
  fetch = "products/fetch/all",
  getById = "products/fetchBy/id/",
  deleteById = "products/deleteBy/id/",
  create = "products/new",
  createList = "products/new/list",
  update = "products/update",
  fetchVariants = "products/fetch/variants",
  newVariant = "products/new/variant",
  createVariantList = "products/new/variant/list",
  updateVariant = "products/update/variant",
  deleteVariantById = "products/delete/variantBy/id/",
  deleteVariantsList = "products/delete/variant/list",
  fetchVariantsByProductId = "products/fetch/variantsBy/productId/",
  fetchVariantById = "products/fetch/variantBy/id/",
}
